name: Actions Package Release

on:
  push:
    branches: 
      - main


jobs:
  release-actions:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.commit.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: prepare
        run: |
          git config --global user.email "tenderly+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: bump version
        working-directory: packages/actions
        run: npm version patch
      - name: install 
        working-directory: packages/actions
        run: npm install

      - run: npm run build
        working-directory: packages/actions

      - name: commit
        id: commit
        working-directory: packages/actions
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

          git add "package.json"
          git add "package-lock.json"
          git commit -m "release actions-$VERSION"
          git tag actions/$VERSION

      - run: cat package.json && cat package-lock.json
        working-directory: packages/actions
      
      - name: push
        run: git push origin && git push origin actions/$VERSION

      - name: publish release
        working-directory: packages/actions
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      
  release-actions-test:
    needs: release-actions
    runs-on: ubuntu-latest
    env:
      VERSION: ${{needs.release-actions.outputs.version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: prepare
        run: |
          git config --global user.email "tenderly+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: bump version
        working-directory: packages/actions-test
        run:  npm version $VERSION

      - name: install 
        working-directory: packages/actions-test
        run: npm update @tenderly/actions && npm install

      - run: npm run build
        working-directory: packages/actions-test

      - name: commit
        working-directory: packages/actions-test
        run: |
          git add "package.json"
          git add "package-lock.json"
          git commit -m "release actions-test-$VERSION"
          git tag actions-test/$VERSION
      - run: cat package.json && cat package-lock.json
        working-directory: packages/actions-test

      - name: push
        run: git push origin && git push origin actions-test/$VERSION

      - name: publish release
        working-directory: packages/actions-test
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

